# Generated by Django 5.2.5 on 2025-08-28 09:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_favoriteshop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteShop',
            new_name='FavouriteShop',
        ),
    ]
