# Generated by Django 5.2.5 on 2025-08-28 09:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_favoriteshop_favouriteshop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteShop',
            new_name='FavoriteShop',
        ),
    ]
