# Generated by Django 5.2.5 on 2025-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_servicewishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='sc_img',
            field=models.ImageField(blank=True, null=True, upload_to='services-category/'),
        ),
    ]
