# Generated by Django 5.2.5 on 2025-09-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_servicecategory_sc_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_verifed',
            field=models.BooleanField(default=False),
        ),
    ]
