# Generated by Django 5.2.5 on 2025-09-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_shop_is_verifed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='is_verifed',
            new_name='is_varified',
        ),
    ]
