# Generated by Django 5.2.5 on 2025-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_is_verifed_shop_is_varified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='is_varified',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='pending', max_length=10),
        ),
    ]
