# Generated by Django 5.2.5 on 2025-09-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_is_varified_shop_is_verified_shop_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='close_days',
            field=models.JSONField(blank=True, default=list, help_text="List of closed days (e.g., ['monday', 'tuesday'])", null=True),
        ),
    ]
